FROM resin/%%RESIN_MACHINE_NAME%%-node:6-slim

ENV INITSYSTEM on

WORKDIR /usr/src/app

RUN npm install --global coffeescript

COPY package.json package.json

RUN JOBS=MAX npm install --production --unsafe-perm && npm cache clean && rm -rf /tmp/*

COPY . ./

CMD ["npm", "start"]
